// Generated by https://quicktype.io

export interface BookModel {
    author:         string;
    collectionId:   string;
    collectionName: string;
    created:        string;
    id:             string;
    title:          string;
    updated:        string;
    year:           number;
    expand:         Expand;
}

export interface Expand {
}
