// Generated by https://quicktype.io

export interface BookListModel {
    page:       number;
    perPage:    number;
    totalPages: number;
    totalItems: number;
    items:      BookModel[];
}

export interface BookModel {
    id:              string;
    collectionId:    string;
    collectionName:  string;
    username:        string;
    verified:        boolean;
    emailVisibility: boolean;
    email:           string;
    created:         string;
    updated:         string;
    name:            string;
    avatar:          string;
}
